// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/etsrc/goprod/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// BookmarkRepository is an autogenerated mock type for the BookmarkRepository type
type BookmarkRepository struct {
	mock.Mock
}

type BookmarkRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BookmarkRepository) EXPECT() *BookmarkRepository_Expecter {
	return &BookmarkRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, b
func (_m *BookmarkRepository) Create(ctx context.Context, b *domain.Bookmark) error {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Bookmark) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BookmarkRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type BookmarkRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - b *domain.Bookmark
func (_e *BookmarkRepository_Expecter) Create(ctx interface{}, b interface{}) *BookmarkRepository_Create_Call {
	return &BookmarkRepository_Create_Call{Call: _e.mock.On("Create", ctx, b)}
}

func (_c *BookmarkRepository_Create_Call) Run(run func(ctx context.Context, b *domain.Bookmark)) *BookmarkRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Bookmark))
	})
	return _c
}

func (_c *BookmarkRepository_Create_Call) Return(_a0 error) *BookmarkRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BookmarkRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Bookmark) error) *BookmarkRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *BookmarkRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BookmarkRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type BookmarkRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *BookmarkRepository_Expecter) Delete(ctx interface{}, id interface{}) *BookmarkRepository_Delete_Call {
	return &BookmarkRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *BookmarkRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *BookmarkRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BookmarkRepository_Delete_Call) Return(_a0 error) *BookmarkRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BookmarkRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *BookmarkRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *BookmarkRepository) GetAll(ctx context.Context) ([]*domain.Bookmark, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*domain.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Bookmark, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Bookmark); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookmarkRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type BookmarkRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *BookmarkRepository_Expecter) GetAll(ctx interface{}) *BookmarkRepository_GetAll_Call {
	return &BookmarkRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *BookmarkRepository_GetAll_Call) Run(run func(ctx context.Context)) *BookmarkRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *BookmarkRepository_GetAll_Call) Return(_a0 []*domain.Bookmark, _a1 error) *BookmarkRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookmarkRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]*domain.Bookmark, error)) *BookmarkRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *BookmarkRepository) GetByID(ctx context.Context, id string) (*domain.Bookmark, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Bookmark, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Bookmark); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookmarkRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type BookmarkRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *BookmarkRepository_Expecter) GetByID(ctx interface{}, id interface{}) *BookmarkRepository_GetByID_Call {
	return &BookmarkRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *BookmarkRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *BookmarkRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BookmarkRepository_GetByID_Call) Return(_a0 *domain.Bookmark, _a1 error) *BookmarkRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookmarkRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.Bookmark, error)) *BookmarkRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewBookmarkRepository creates a new instance of BookmarkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookmarkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookmarkRepository {
	mock := &BookmarkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
