// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/etsrc/goprod/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// BookmarkService is an autogenerated mock type for the BookmarkService type
type BookmarkService struct {
	mock.Mock
}

type BookmarkService_Expecter struct {
	mock *mock.Mock
}

func (_m *BookmarkService) EXPECT() *BookmarkService_Expecter {
	return &BookmarkService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, b
func (_m *BookmarkService) Create(ctx context.Context, b *domain.Bookmark) error {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Bookmark) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BookmarkService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type BookmarkService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - b *domain.Bookmark
func (_e *BookmarkService_Expecter) Create(ctx interface{}, b interface{}) *BookmarkService_Create_Call {
	return &BookmarkService_Create_Call{Call: _e.mock.On("Create", ctx, b)}
}

func (_c *BookmarkService_Create_Call) Run(run func(ctx context.Context, b *domain.Bookmark)) *BookmarkService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Bookmark))
	})
	return _c
}

func (_c *BookmarkService_Create_Call) Return(_a0 error) *BookmarkService_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BookmarkService_Create_Call) RunAndReturn(run func(context.Context, *domain.Bookmark) error) *BookmarkService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *BookmarkService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BookmarkService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type BookmarkService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *BookmarkService_Expecter) Delete(ctx interface{}, id interface{}) *BookmarkService_Delete_Call {
	return &BookmarkService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *BookmarkService_Delete_Call) Run(run func(ctx context.Context, id string)) *BookmarkService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BookmarkService_Delete_Call) Return(_a0 error) *BookmarkService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BookmarkService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *BookmarkService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *BookmarkService) GetByID(ctx context.Context, id string) (*domain.Bookmark, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Bookmark, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Bookmark); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookmarkService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type BookmarkService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *BookmarkService_Expecter) GetByID(ctx interface{}, id interface{}) *BookmarkService_GetByID_Call {
	return &BookmarkService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *BookmarkService_GetByID_Call) Run(run func(ctx context.Context, id string)) *BookmarkService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BookmarkService_GetByID_Call) Return(_a0 *domain.Bookmark, _a1 error) *BookmarkService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookmarkService_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.Bookmark, error)) *BookmarkService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *BookmarkService) List(ctx context.Context) ([]*domain.Bookmark, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Bookmark, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Bookmark); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BookmarkService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type BookmarkService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *BookmarkService_Expecter) List(ctx interface{}) *BookmarkService_List_Call {
	return &BookmarkService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *BookmarkService_List_Call) Run(run func(ctx context.Context)) *BookmarkService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *BookmarkService_List_Call) Return(_a0 []*domain.Bookmark, _a1 error) *BookmarkService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BookmarkService_List_Call) RunAndReturn(run func(context.Context) ([]*domain.Bookmark, error)) *BookmarkService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewBookmarkService creates a new instance of BookmarkService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookmarkService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookmarkService {
	mock := &BookmarkService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
