// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ServerInterface is an autogenerated mock type for the ServerInterface type
type ServerInterface struct {
	mock.Mock
}

type ServerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ServerInterface) EXPECT() *ServerInterface_Expecter {
	return &ServerInterface_Expecter{mock: &_m.Mock}
}

// CreateBookmark provides a mock function with given fields: w, r
func (_m *ServerInterface) CreateBookmark(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ServerInterface_CreateBookmark_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBookmark'
type ServerInterface_CreateBookmark_Call struct {
	*mock.Call
}

// CreateBookmark is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *ServerInterface_Expecter) CreateBookmark(w interface{}, r interface{}) *ServerInterface_CreateBookmark_Call {
	return &ServerInterface_CreateBookmark_Call{Call: _e.mock.On("CreateBookmark", w, r)}
}

func (_c *ServerInterface_CreateBookmark_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *ServerInterface_CreateBookmark_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *ServerInterface_CreateBookmark_Call) Return() *ServerInterface_CreateBookmark_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServerInterface_CreateBookmark_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *ServerInterface_CreateBookmark_Call {
	_c.Run(run)
	return _c
}

// DeleteBookmark provides a mock function with given fields: w, r, id
func (_m *ServerInterface) DeleteBookmark(w http.ResponseWriter, r *http.Request, id string) {
	_m.Called(w, r, id)
}

// ServerInterface_DeleteBookmark_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBookmark'
type ServerInterface_DeleteBookmark_Call struct {
	*mock.Call
}

// DeleteBookmark is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - id string
func (_e *ServerInterface_Expecter) DeleteBookmark(w interface{}, r interface{}, id interface{}) *ServerInterface_DeleteBookmark_Call {
	return &ServerInterface_DeleteBookmark_Call{Call: _e.mock.On("DeleteBookmark", w, r, id)}
}

func (_c *ServerInterface_DeleteBookmark_Call) Run(run func(w http.ResponseWriter, r *http.Request, id string)) *ServerInterface_DeleteBookmark_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request), args[2].(string))
	})
	return _c
}

func (_c *ServerInterface_DeleteBookmark_Call) Return() *ServerInterface_DeleteBookmark_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServerInterface_DeleteBookmark_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request, string)) *ServerInterface_DeleteBookmark_Call {
	_c.Run(run)
	return _c
}

// GetAllBookmarks provides a mock function with given fields: w, r
func (_m *ServerInterface) GetAllBookmarks(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ServerInterface_GetAllBookmarks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBookmarks'
type ServerInterface_GetAllBookmarks_Call struct {
	*mock.Call
}

// GetAllBookmarks is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *ServerInterface_Expecter) GetAllBookmarks(w interface{}, r interface{}) *ServerInterface_GetAllBookmarks_Call {
	return &ServerInterface_GetAllBookmarks_Call{Call: _e.mock.On("GetAllBookmarks", w, r)}
}

func (_c *ServerInterface_GetAllBookmarks_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *ServerInterface_GetAllBookmarks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *ServerInterface_GetAllBookmarks_Call) Return() *ServerInterface_GetAllBookmarks_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServerInterface_GetAllBookmarks_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *ServerInterface_GetAllBookmarks_Call {
	_c.Run(run)
	return _c
}

// GetBookmarkByID provides a mock function with given fields: w, r, id
func (_m *ServerInterface) GetBookmarkByID(w http.ResponseWriter, r *http.Request, id string) {
	_m.Called(w, r, id)
}

// ServerInterface_GetBookmarkByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookmarkByID'
type ServerInterface_GetBookmarkByID_Call struct {
	*mock.Call
}

// GetBookmarkByID is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - id string
func (_e *ServerInterface_Expecter) GetBookmarkByID(w interface{}, r interface{}, id interface{}) *ServerInterface_GetBookmarkByID_Call {
	return &ServerInterface_GetBookmarkByID_Call{Call: _e.mock.On("GetBookmarkByID", w, r, id)}
}

func (_c *ServerInterface_GetBookmarkByID_Call) Run(run func(w http.ResponseWriter, r *http.Request, id string)) *ServerInterface_GetBookmarkByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request), args[2].(string))
	})
	return _c
}

func (_c *ServerInterface_GetBookmarkByID_Call) Return() *ServerInterface_GetBookmarkByID_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServerInterface_GetBookmarkByID_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request, string)) *ServerInterface_GetBookmarkByID_Call {
	_c.Run(run)
	return _c
}

// NewServerInterface creates a new instance of ServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServerInterface {
	mock := &ServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
