// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ServeMux is an autogenerated mock type for the ServeMux type
type ServeMux struct {
	mock.Mock
}

type ServeMux_Expecter struct {
	mock *mock.Mock
}

func (_m *ServeMux) EXPECT() *ServeMux_Expecter {
	return &ServeMux_Expecter{mock: &_m.Mock}
}

// HandleFunc provides a mock function with given fields: pattern, handler
func (_m *ServeMux) HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request)) {
	_m.Called(pattern, handler)
}

// ServeMux_HandleFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleFunc'
type ServeMux_HandleFunc_Call struct {
	*mock.Call
}

// HandleFunc is a helper method to define mock.On call
//   - pattern string
//   - handler func(http.ResponseWriter , *http.Request)
func (_e *ServeMux_Expecter) HandleFunc(pattern interface{}, handler interface{}) *ServeMux_HandleFunc_Call {
	return &ServeMux_HandleFunc_Call{Call: _e.mock.On("HandleFunc", pattern, handler)}
}

func (_c *ServeMux_HandleFunc_Call) Run(run func(pattern string, handler func(http.ResponseWriter, *http.Request))) *ServeMux_HandleFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(func(http.ResponseWriter, *http.Request)))
	})
	return _c
}

func (_c *ServeMux_HandleFunc_Call) Return() *ServeMux_HandleFunc_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServeMux_HandleFunc_Call) RunAndReturn(run func(string, func(http.ResponseWriter, *http.Request))) *ServeMux_HandleFunc_Call {
	_c.Run(run)
	return _c
}

// ServeHTTP provides a mock function with given fields: w, r
func (_m *ServeMux) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ServeMux_ServeHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeHTTP'
type ServeMux_ServeHTTP_Call struct {
	*mock.Call
}

// ServeHTTP is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *ServeMux_Expecter) ServeHTTP(w interface{}, r interface{}) *ServeMux_ServeHTTP_Call {
	return &ServeMux_ServeHTTP_Call{Call: _e.mock.On("ServeHTTP", w, r)}
}

func (_c *ServeMux_ServeHTTP_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *ServeMux_ServeHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *ServeMux_ServeHTTP_Call) Return() *ServeMux_ServeHTTP_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServeMux_ServeHTTP_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *ServeMux_ServeHTTP_Call {
	_c.Run(run)
	return _c
}

// NewServeMux creates a new instance of ServeMux. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServeMux(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServeMux {
	mock := &ServeMux{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
