run:
  timeout: 5m

linters:
  enable:
    - errcheck      # Check for unhandled errors
    - gosimple      # Suggest simpler code
    - govet         # Standard Go vet tool
    - staticcheck   # Advanced static analysis
    - unused        # Finds unused constants/variables/functions
    - revive        # Modern replacement for golint
    - misspell      # Finds common spelling mistakes
    - paralleltest  # Detects missing usage of t.Parallel() method in your Go test
    - cyclop        # Checks function and package cyclomatic complexity
    - gosec         # Inspects source code for security problems


issues:
  issues.exclude-dirs:
    - internal/infra/transport/rest/gen
    - internal/mocks  
  exclude-rules:
    # Relax rules for test files
    - path: _test\.go
      linters:
        - errcheck
