version: '3'

tasks:
  init:
    desc: Set up local development environment
    cmds:
      # 1. Setup Git Hooks
      - mkdir -p .git/hooks
      - cp scripts/pre-commit .git/hooks/pre-commit
      - chmod +x .git/hooks/pre-commit
      # 2. Pre-download dependencies and tools
      - go mod download
      - task: tidy
      - echo "✅ Environment ready! Git hooks installed and dependencies cached."

  generate:
    desc: Run all code generation (OpenAPI and Mocks)
    cmds:
      - go generate ./...
    sources:
      - api/openapi.yaml
      - internal/domain/**/*.go
    generates:
      - internal/infra/transport/rest/gen/*.go
      - internal/mocks/*.go

  docker:build:
    desc: Build the production docker image
    cmds:
      - podman build -t goprod .

  docker:run:
    desc: Run the built container
    cmds:
      - podman run --rm --name goprod -p 8080:8080 goprod

  db:start:
    desc: Start a Postgres container
    status:
      - podman ps | grep goprod-db
    cmds:
      - |
        podman run --name goprod-db \
          -e POSTGRES_PASSWORD=postgres \
          -e POSTGRES_DB=goprod \
          -p 5432:5432 \
          -d docker.io/library/postgres:16-alpine
      - echo "Waiting for database to start..."
      - sleep 5

  db:stop:
    desc: Stop and remove the Postgres container
    cmds:
      - podman stop goprod-db
      - podman rm goprod-db

  db:logs:
    desc: Tail database logs
    cmds:
      - podman logs -f goprod-db

  db:cli:
    desc: Open interactive Postgres CLI
    cmds:
      - podman exec -it goprod-db psql -U postgres -d goprod

  migrate:up:
    desc: Start DB and apply all Postgres migrations
    deps: [db:start]
    cmds:
      # Use 'go run' with the -tags flag to include the postgres driver
      - go run -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate -path internal/infra/persistence/postgres/migrations -database "postgres://postgres:postgres@localhost:5432/goprod?sslmode=disable" up

  migrate:drop:
    desc: Drop all tables and migrations (Clean Slate)
    cmds:
      # The 'drop' command removes everything including the schema_migrations table
      - go run -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate -path internal/infra/persistence/postgres/migrations -database "postgres://postgres:postgres@localhost:5432/goprod?sslmode=disable" drop -f

  migrate:reset:
    desc: Drop everything and re-apply all migrations
    cmds:
      - task: migrate:drop
      - task: migrate:up

  migrate:new:
    desc: Create a new migration file (usage task migrate:new NAME=add_fields)
    cmds:
      - mkdir -p internal/infra/persistence/postgres/migrations
      - go tool migrate create -ext sql -dir internal/infra/persistence/postgres/migrations -seq {{.NAME}}

  db:seed:
    desc: Insert example bookmarks into the database
    cmds:
      - |
        podman exec -i goprod-db psql -U postgres -d goprod < internal/infra/persistence/postgres/scripts/seed.sql
      - echo "Database seeded successfully!"

  lint:
    desc: Run linter
    sources:
      - "**/*.go"
      - ".golangci.yml"
    exclude:
      - "internal/infra/transport/rest/gen/**/*.go"
      - "internal/mocks/**/*.go"
    cmds:
      - go tool golangci-lint run ./...

  lint:fix:
    desc: Automatically fix linter issues where possible
    cmds:
      - go tool golangci-lint run --fix

  test:
    desc: Run all tests with race detection and cache cleared
    cmds:
      - go test -v -race -count=1 ./...

  check:
    desc: Run lint and tests together
    deps: [lint, test]

  build:
    desc: Build the application binary
    cmds:
      - go build -o bin/app cmd/main.go

  tidy:
    desc: Clean up and sync Go dependencies
    cmds:
      - go mod tidy

  all:
    desc: Regenerate everything and run all checks
    cmds:
      - task: tidy
      - task: generate
      - task: check
