version: '3'

tasks:
  generate:
    desc: Run all code generation (OpenAPI and Mocks)
    cmds:
      - go generate ./...
    sources:
      - api/openapi.yaml
      - internal/domain/**/*.go
    generates:
      - internal/infra/transport/rest/gen/*.go
      - internal/mocks/*.go

  docker:build:
    desc: Build the production docker image
    cmds:
      - podman build -t goprod .

  docker:run:
    desc: Run the built container
    cmds:
      - podman run --rm --name goprod -p 8080:8080 goprod

  lint:
    desc: Run linter
    sources:
      - "**/*.go"
      - ".golangci.yml"
    exclude:
      - "internal/infra/transport/rest/gen/**/*.go"
      - "internal/mocks/**/*.go"
    cmds:
      - go tool golangci-lint run ./...

  lint:fix:
    desc: Automatically fix linter issues where possible
    cmds:
      - go tool golangci-lint run --fix

  test:
    desc: Run all tests with race detection and cache cleared
    cmds:
      - go test -v -race -count=1 ./...

  check:
    desc: Run lint and tests together
    deps: [lint, test]

  build:
    desc: Build the application binary
    cmds:
      - go build -o bin/app cmd/main.go

  all:
    desc: Regenerate everything and run all checks
    cmds:
      - task: generate
      - task: check
